using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RegMan.Backend.DAL.Entities
{
    [Table("OfficeHourCompletionQrTokens")]
    public class OfficeHourQrToken
    {
        [Key]
        [Column("OfficeHourCompletionQrTokenId")]
        public int QrTokenId { get; set; }

        [Required]
        [Column("OfficeHourQueueEntryId")]
        public int QueueEntryId { get; set; }

        // Rotation state: only valid while QueueEntry is Ready
        public Guid? CurrentNonce { get; set; }
        public DateTime? IssuedAtUtc { get; set; }
        public DateTime? ExpiresAtUtc { get; set; }

        // One-time use marker
        public DateTime? UsedAtUtc { get; set; }
        public string? UsedByUserId { get; set; }

        // Existing schema requires TokenHash (unique, non-null). This will be generated by DB default.
        [Column("TokenHash")]
        [MaxLength(450)]
        public string TokenHash { get; set; } = null!;

        public OfficeHourQueueEntry QueueEntry { get; set; } = null!;
    }
}
